#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import <objc/runtime.h>

static NSUInteger gDumpIndex;
static NSString *YTGRect(CGRect r){return NSStringFromCGRect(r);}
static NSString *YTGColor(UIColor *c){if(!c)return @"nil";CGFloat r,g,b,a,w;if([c getRed:&r green:&g blue:&b alpha:&a])return [NSString stringWithFormat:@"rgba %.3f %.3f %.3f %.3f",r,g,b,a];if([c getWhite:&w alpha:&a])return [NSString stringWithFormat:@"white %.3f %.3f",w,a];return c.description;}
static NSString *YTGEffect(UIView *v){if(![v isKindOfClass:UIVisualEffectView.class])return @"-";id e=((UIVisualEffectView*)v).effect;NSString*n=e?NSStringFromClass([e class]):@"nil";@try{if([e respondsToSelector:NSSelectorFromString(@"style")])n=[n stringByAppendingFormat:@" style=%@",[e valueForKey:@"style"]];if([e respondsToSelector:NSSelectorFromString(@"interactive")])n=[n stringByAppendingFormat:@" interactive=%@",[e valueForKey:@"interactive"]];}@catch(__unused id ex){}return n;}
static BOOL YTGRelevant(UIView*v,UIWindow*w){NSString*n=NSStringFromClass(v.class);CGRect r=[v convertRect:v.bounds toView:w];CGFloat H=w.bounds.size.height;return CGRectGetMaxY(r)>H-430||[n localizedCaseInsensitiveContainsString:@"pivot"]||[n localizedCaseInsensitiveContainsString:@"frost"]||[n localizedCaseInsensitiveContainsString:@"glass"]||[n localizedCaseInsensitiveContainsString:@"bottom"]||[n localizedCaseInsensitiveContainsString:@"tabbar"]||[n localizedCaseInsensitiveContainsString:@"mini"]||[v isKindOfClass:UIVisualEffectView.class];}
static NSString *YTGGestures(UIView*v){if(!v.gestureRecognizers.count)return @"-";NSMutableArray*a=[NSMutableArray array];for(UIGestureRecognizer*g in v.gestureRecognizers)[a addObject:[NSString stringWithFormat:@"%@:%ld:%d",NSStringFromClass(g.class),(long)g.state,g.enabled]];return [a componentsJoinedByString:@","];}
static void YTGWalk(UIView*v,UIWindow*w,NSUInteger depth,NSMutableString*out){if(YTGRelevant(v,w)){CGRect win=[v convertRect:v.bounds toView:w];[out appendFormat:@"%*s%@ <%p> frame=%@ win=%@ bounds=%@ alpha=%.3f hidden=%d opaque=%d clips=%d UI=%d bg=%@ effect=[%@] layer=%@ gestures=[%@] super=%@ sub=%lu\n",(int)MIN(depth,30)*2,"",NSStringFromClass(v.class),v,YTGRect(v.frame),YTGRect(win),YTGRect(v.bounds),v.alpha,v.hidden,v.opaque,v.clipsToBounds,v.userInteractionEnabled,YTGColor(v.backgroundColor),YTGEffect(v),NSStringFromClass(v.layer.class),YTGGestures(v),NSStringFromClass(v.superview.class),(unsigned long)v.subviews.count];}for(UIView*s in v.subviews)YTGWalk(s,w,depth+1,out);}
static void YTGDump(NSString *reason){NSMutableString*out=[NSMutableString stringWithFormat:@"\n\n========== DUMP %lu %@ %@ state=%ld ==========\n",(unsigned long)++gDumpIndex,NSDate.date,reason,(long)UIApplication.sharedApplication.applicationState];for(UIScene*scene in UIApplication.sharedApplication.connectedScenes)if([scene isKindOfClass:UIWindowScene.class]){[out appendFormat:@"SCENE %@ activation=%ld orientation=%ld\n",scene.session.persistentIdentifier,(long)scene.activationState,(long)((UIWindowScene*)scene).interfaceOrientation];for(UIWindow*w in ((UIWindowScene*)scene).windows){[out appendFormat:@"WINDOW <%p> key=%d level=%.1f frame=%@ root=%@\n",w,w.keyWindow,w.windowLevel,YTGRect(w.frame),NSStringFromClass(w.rootViewController.class)];YTGWalk(w,w,0,out);}}NSArray*d=NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES);if(!d.count)return;NSString*p=[d[0]stringByAppendingPathComponent:@"YouTubeGlass-Hierarchy.txt"];if(gDumpIndex==1)[out writeToFile:p atomically:YES encoding:NSUTF8StringEncoding error:nil];else{NSFileHandle*h=[NSFileHandle fileHandleForWritingAtPath:p];[h seekToEndOfFile];[h writeData:[out dataUsingEncoding:NSUTF8StringEncoding]];[h closeFile];}}
__attribute__((constructor)) static void YTGDiagnosticStart(void){dispatch_async(dispatch_get_main_queue(),^{for(NSNumber*d in @[@0.2,@1.0,@3.0,@6.0,@10.0,@15.0,@25.0,@40.0,@60.0])dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(d.doubleValue*NSEC_PER_SEC)),dispatch_get_main_queue(),^{YTGDump([NSString stringWithFormat:@"timer-%@",d]);});NSNotificationCenter*c=NSNotificationCenter.defaultCenter;[c addObserverForName:UIApplicationDidBecomeActiveNotification object:nil queue:NSOperationQueue.mainQueue usingBlock:^(__unused NSNotification*n){dispatch_after(dispatch_time(DISPATCH_TIME_NOW,NSEC_PER_SEC),dispatch_get_main_queue(),^{YTGDump(@"didBecomeActive");});}];[c addObserverForName:UIApplicationDidEnterBackgroundNotification object:nil queue:NSOperationQueue.mainQueue usingBlock:^(__unused NSNotification*n){YTGDump(@"didEnterBackground");}];});}
